dist: trusty
language: clojure

services:
  - docker

stages:
  - build
  - integrationtest

env:
  global:
    - DOCKER_USERNAME: domaindrivenarchitecture
    - secure: "I0Ncp7Mv2mAEStsaQo+GqPmPRyFsddm2PQFsxGhIYuHOEm0mN4cAhLvtZCGRMVAEdaN2KJJ0w4x9dNEVUrCaWX66vHqVqWkSVVfjbLVzW4Yf27gpiZAXwj+4UbsBZ5on3GG40Isf6jOBYKTqfjJgm9TpmxGLfaWWHhadsAGGgAe6BX77O4ztZfeMtTYPTY+aLNyNvTF63UJ8KnunO/gByaVNZk/v8rSI13Ea3wLtw5zwDLjJiUz+zQmUpOuMEWaLFd3lMb6uJ5gxZav4HlmVIxydzdpER0+4GAT2EMoYhWxR1TeNKbPHsh6dkuE8oHyW6lCwAkrMkt4MjRYyHbPA9eDvZMxgXnUmChBk3QmRPXJmY/ilqjvXkezF5hM+acAYvHCC5uvTO3qApl3MLiaLFwBWo4wTiD/SHKeMzIm4dgmHdneW5VNHQJ3SkF0V2o349Qqm8/u6pjiOXwxGYtutwfIYiRTtjiKZcjd39Va9CKDJsXoD8hDc+TH5Qv30YTo071myxQI14m/D0lQPKJF751b38zpgxb/t80gHNoDfWnvIahCqeIzQVOsozszDdz3yB2PWwXjDz1D14Z9hcMWS2tJG1GtBc38LKhZ7uWLpVPp6kpbeCKzkVk7VTW+aiXYQbhmsCWoPQl/gZlCtNzGOQsbl+pr3bl+7f0U2Ws+GHww="

jobs:
  include:
    - stage: build
      script:
        - # build
        - lein test
        - lein uberjar
        - md5sum target/dda-smeagol-standalone.jar > target/dda-smeagol-standalone.jar.md5
        - # create docker image
        - docker build -t dda-smeagol-crate --file integration/docker/image/Dockerfile .
        - # integration test on docker image level
        - docker build -t dda-smeagol-crate-test --file integration/docker/test/Dockerfile .
      deploy:
        skip_cleanup: true
        provider: releases
        overwrite: true
        draft: true
        api_key:
          secure: "PytWrT6c/R49peVfQkiHHgDH3zUVENDcIHQ7L42TRlvETKHcc5zA2krtN6EbGAnhNe0KMl+YdZQpPJyAQJH1sd9n+c1XVytwnbdQ/j9CACB8j8X/i9D6OBBMLaVod4N9OO6rs415UFnfQw87XTorcKJamAunEIQgYFgxWvbJS/PCiP2E7H/o28fdIt3uTFKaVhab6FS1PG87Pnfxniowgn8S4BisyE86REnR4kodQraD4ApkD3AXmKfsvJ7QY48PSboF+AdoIXo4p8m4TFQhQUOwMYG0+m31qv/S8PAWPAPFalqDJPR204X1jImo9xe2IpnprMgNUEit/jH+Q22ts3ZsCFPSU0knlFe6ecaplV9+0958uhcR4XXBFWDWj1/ynMisXtsufGtkvPDup3a5wKItuv21T/lMiK9zZZNtwsCmcqhvbM3oNvrEO6DueeBukKICijcJIMEIOk1mlcdsscC45AcK2kcvdtCAuVx9HToKomoaQUfcNOAP8S2o69RQmytMKplVD+vCKHdepc2P9jg9ksQ3S5bgwaZMqg8zWUGOMnW49Nw0BotAOp3Y1AKAi/gAj4/1fNbkWR8YFnfHDgexbt0T2tJG+YLOzaDY0/YcPJvNoVSHaJ8vpFYVmoXPka9M5ztdFoRnMeUFPMTmLj38Cd1Ht76J1ueK11Qzk3Y="
        file:
          - target/dda-smeagol-standalone.jar
          - target/dda-smeagol-standalone.jar.md5
        provider: script
        script: bash integration/docker/publish.sh dda-smeagol-crate
